version: "3.1"

services:
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: no
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm
  redis:
    container_name: redisStorage
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - batya_botnet
    volumes:
      - /path/to/redis-persistence:/bitnami/redis/data
  bot:
    container_name: wishly
    build:
      context: .
    command: python bot.py
    restart: always
    networks:
      - batya_botnet
    depends_on:
      - redisStorage
    env_file:
      - ".env"
    volumes:
      - .:/src

networks:
  batya_botnet:
    external: true