version: "3.1"

services:
  redis:
    container_name: redisStorage
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - batya_botnet
    volumes:
      - /path/to/redis-persistence:/bitnami/redis/data
  bot:
    container_name: wishly
    build:
      context: .
    command: python bot.py
    restart: always
    networks:
      - batya_botnet
    env_file:
      - ".env"
    volumes:
      - .:/src

networks:
  batya_botnet:
    external: true