version: "3.8"

services:
  redis:
    image: 'redis:latest'
    container_name: redis-wishly
    ports:
      - "6379:6379"
    networks:
      - botnet
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    image: postgres
    container_name: postgres-wishly
    env_file:
      - "./.env"
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/code
    networks:
      - botnet
    command: -p 5433

  bot:
    container_name: wishly
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - "./.env"
    restart: always
    depends_on:
      - redis
      - postgres
    networks:
      - botnet
    volumes:
      - .:/code

networks:
  botnet: