version: "3.1"

services:
  bot:
    container_name: wishly
    build:
      context: .
    command: python bot.py
    restart: always
    networks:
      - batya_botnet
    env_file:
      - ".env"
    volumes:
      - .:/src

  redis:
    container_name: redis_wishly
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  batya_botnet:
    external: true