"""empty message

Revision ID: 157a543983db
Revises: d77eea3c0a21
Create Date: 2023-12-18 22:02:41.982183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157a543983db'
down_revision: Union[str, None] = 'd77eea3c0a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('wishlist_purpose', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlists', 'wishlist_purpose')
    # ### end Alembic commands ###
