"""Creating tables users, wishlists, items, wishlist_user_association

Revision ID: 1ab9fbc1fa0b
Revises: dcddf0340718
Create Date: 2023-11-26 10:32:46.768593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab9fbc1fa0b'
down_revision: Union[str, None] = 'dcddf0340718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('deep_link', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('hashcode', sa.String(length=6), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashcode')
    )
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('photo_link', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('photo_file_id', sa.String(length=200), nullable=True),
    sa.Column('thumb_link', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist_user_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_user_association')
    op.drop_table('items')
    op.drop_table('wishlists')
    op.drop_table('users')
    # ### end Alembic commands ###
