"""add ondelete=CASCADE property

Revision ID: 69f2d1f86220
Revises: a6f6f4807b4e
Create Date: 2023-12-03 13:06:26.417628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f2d1f86220'
down_revision: Union[str, None] = 'a6f6f4807b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wishlist_user_association_user_id_fkey', 'wishlist_user_association', type_='foreignkey')
    op.drop_constraint('wishlist_user_association_wishlist_id_fkey', 'wishlist_user_association', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist_user_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wishlist_user_association', 'wishlists', ['wishlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist_user_association', type_='foreignkey')
    op.drop_constraint(None, 'wishlist_user_association', type_='foreignkey')
    op.create_foreign_key('wishlist_user_association_wishlist_id_fkey', 'wishlist_user_association', 'wishlists', ['wishlist_id'], ['id'])
    op.create_foreign_key('wishlist_user_association_user_id_fkey', 'wishlist_user_association', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
