"""empty message

Revision ID: 7e7bd76edba5
Revises: b36c612dfecb
Create Date: 2023-12-17 12:07:10.412761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7bd76edba5'
down_revision: Union[str, None] = 'b36c612dfecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gift_ideas_gift_idea_category_id_fkey', 'gift_ideas', type_='foreignkey')
    op.create_foreign_key(None, 'gift_ideas', 'gift_idea_categories', ['gift_idea_category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('items_wishlist_id_fkey', 'items', type_='foreignkey')
    op.drop_constraint('items_customer_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'wishlists', ['wishlist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'items', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('secret_list_participants_user_id_fkey', 'secret_list_participants', type_='foreignkey')
    op.drop_constraint('secret_list_participants_secret_list_id_fkey', 'secret_list_participants', type_='foreignkey')
    op.drop_constraint('secret_list_participants_giver_participant_id_fkey', 'secret_list_participants', type_='foreignkey')
    op.create_foreign_key(None, 'secret_list_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'secret_list_participants', 'secret_lists', ['secret_list_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'secret_list_participants', 'secret_list_participants', ['giver_participant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('secret_lists_creator_id_fkey', 'secret_lists', type_='foreignkey')
    op.create_foreign_key(None, 'secret_lists', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('wishlists_creator_id_fkey', 'wishlists', type_='foreignkey')
    op.create_foreign_key(None, 'wishlists', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', type_='foreignkey')
    op.create_foreign_key('wishlists_creator_id_fkey', 'wishlists', 'users', ['creator_id'], ['id'])
    op.drop_constraint(None, 'secret_lists', type_='foreignkey')
    op.create_foreign_key('secret_lists_creator_id_fkey', 'secret_lists', 'users', ['creator_id'], ['id'])
    op.drop_constraint(None, 'secret_list_participants', type_='foreignkey')
    op.drop_constraint(None, 'secret_list_participants', type_='foreignkey')
    op.drop_constraint(None, 'secret_list_participants', type_='foreignkey')
    op.create_foreign_key('secret_list_participants_giver_participant_id_fkey', 'secret_list_participants', 'secret_list_participants', ['giver_participant_id'], ['id'])
    op.create_foreign_key('secret_list_participants_secret_list_id_fkey', 'secret_list_participants', 'secret_lists', ['secret_list_id'], ['id'])
    op.create_foreign_key('secret_list_participants_user_id_fkey', 'secret_list_participants', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_customer_id_fkey', 'items', 'users', ['customer_id'], ['id'])
    op.create_foreign_key('items_wishlist_id_fkey', 'items', 'wishlists', ['wishlist_id'], ['id'])
    op.drop_constraint(None, 'gift_ideas', type_='foreignkey')
    op.create_foreign_key('gift_ideas_gift_idea_category_id_fkey', 'gift_ideas', 'gift_idea_categories', ['gift_idea_category_id'], ['id'])
    # ### end Alembic commands ###
