"""empty message

Revision ID: b36c612dfecb
Revises: d2f8ae7678b0
Create Date: 2023-12-17 08:22:52.946706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36c612dfecb'
down_revision: Union[str, None] = 'd2f8ae7678b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('secret_list_items_participant_id_fkey', 'secret_list_items', type_='foreignkey')
    op.create_foreign_key(None, 'secret_list_items', 'secret_list_participants', ['participant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'secret_list_items', type_='foreignkey')
    op.create_foreign_key('secret_list_items_participant_id_fkey', 'secret_list_items', 'secret_list_participants', ['participant_id'], ['id'])
    # ### end Alembic commands ###
