"""Created table secret_lists_user_association

Revision ID: b7f0fd6136ce
Revises: 89f844a75311
Create Date: 2023-12-15 17:17:43.257926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f0fd6136ce'
down_revision: Union[str, None] = '89f844a75311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_list_user_association',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('secret_list_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['secret_list_id'], ['secret_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_list_user_association')
    # ### end Alembic commands ###
