"""empty message

Revision ID: d2f8ae7678b0
Revises: b7f0fd6136ce
Create Date: 2023-12-16 18:20:59.654098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f8ae7678b0'
down_revision: Union[str, None] = 'b7f0fd6136ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_list_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('secret_list_id', sa.Integer(), nullable=True),
    sa.Column('giver_participant_id', sa.BigInteger(), nullable=True),
    sa.Column('is_gift_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['giver_participant_id'], ['secret_list_participants.id'], ),
    sa.ForeignKeyConstraint(['secret_list_id'], ['secret_lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('photo_link', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('photo_file_id', sa.String(length=200), nullable=True),
    sa.Column('thumb_link', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['secret_list_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('secret_list_user_association')
    op.add_column('secret_lists', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secret_lists', 'status')
    op.create_table('secret_list_user_association',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('secret_list_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['secret_list_id'], ['secret_lists.id'], name='secret_list_user_association_secret_list_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='secret_list_user_association_user_id_fkey', ondelete='CASCADE')
    )
    op.drop_table('secret_list_items')
    op.drop_table('secret_list_participants')
    # ### end Alembic commands ###
