"""empty message

Revision ID: d77eea3c0a21
Revises: 5f85c96d396a
Create Date: 2023-12-17 19:05:50.556125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77eea3c0a21'
down_revision: Union[str, None] = '5f85c96d396a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'wishlists', ['participant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', type_='unique')
    # ### end Alembic commands ###
