"""empty message

Revision ID: dca364cfb421
Revises: f73d3b54f5af
Create Date: 2023-12-19 15:50:17.939108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca364cfb421'
down_revision: Union[str, None] = 'f73d3b54f5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('wishlists', sa.Column('purpose', sa.String(length=30), nullable=True))
    op.drop_column('wishlists', 'wishlist_purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('wishlist_purpose', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('wishlists', 'purpose')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
