"""New table secret_lists

Revision ID: ee2b0a7ff57f
Revises: 489937745f66
Create Date: 2023-12-15 14:13:29.501245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2b0a7ff57f'
down_revision: Union[str, None] = '489937745f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_lists',
    sa.Column('users_limit', sa.Integer(), nullable=True),
    sa.Column('gifts_limit', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('hashcode', sa.String(length=6), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashcode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_lists')
    # ### end Alembic commands ###
