"""empty message

Revision ID: f73d3b54f5af
Revises: 157a543983db
Create Date: 2023-12-19 12:30:13.733374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f73d3b54f5af'
down_revision: Union[str, None] = '157a543983db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wishlists_participant_id_fkey', 'wishlists', type_='foreignkey')
    op.drop_constraint('wishlists_participant_id_key', 'wishlists', type_='unique')
    op.drop_column('wishlists', 'participant_id')
    op.drop_table('secret_list_items')
    op.drop_table('secret_list_participants')
    op.drop_table('secret_lists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('wishlists_participant_id_fkey', 'wishlists', 'secret_list_participants', ['participant_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('wishlists_participant_id_key', 'wishlists', ['participant_id'])
    op.create_table('secret_list_participants',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('secret_list_participants_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('secret_list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('giver_participant_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('wishlist_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['giver_participant_id'], ['secret_list_participants.id'], name='secret_list_participants_giver_participant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secret_list_id'], ['secret_lists.id'], name='secret_list_participants_secret_list_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='secret_list_participants_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], name='secret_list_participants_wishlist_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='secret_list_participants_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('secret_list_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('photo_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('photo_file_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('thumb_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['secret_list_participants.id'], name='secret_list_items_participant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='secret_list_items_pkey')
    )
    op.create_table('secret_lists',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('hashcode', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_gifts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='secret_lists_creator_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='secret_lists_pkey'),
    sa.UniqueConstraint('hashcode', name='secret_lists_hashcode_key')
    )
    # ### end Alembic commands ###
